### ISSUE TITLE
Using the Layout Engine

### ISSUE THREAD

**Issue by omairqazi** [HaikuArchives/Randomizer#4]
Hi !
It would be nice to change the code to use the layout engine instead of hardcoding to improve the UI.
Thanks!

**Comment by janus2** [comment]
## RFC

![layout](https://user-images.githubusercontent.com/10423645/48476482-7925d780-e7ff-11e8-921f-06ef9d717f07.png)

**Comment by humdingerb** [comment]
Nice. Maybe use "Special characters" instead of "Special".
If it's known what "Custom" is supposed to do, adding a tool tip would be nice.
The label "Password settings" isn't strictly needed, I think.
